services:
  internal_api:
    build:
      context: .
      dockerfile: api/internal/Dockerfile
    ports:
      - "8000:8000"
    container_name: internal_api

  external_api:
    build:
      context: .
      dockerfile: api/external/Dockerfile
    ports:
      - "8001:8001"
    container_name: external_api

  ui:
    build:
      context: .
      dockerfile: ui/Dockerfile
    ports:
      - "8080:8080"
    container_name: ui