services:
  internal_api:
    build:
      context: .
      dockerfile: api/internal/Dockerfile
    ports:
      - "8000:8000"

  external_api:
    build:
      context: .
      dockerfile: api/external/Dockerfile
    ports:
      - "8001:8001"

  ui:
    build:
      context: .
      dockerfile: ui/Dockerfile
    ports:
      - "8080:8080"